# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZzangGeun's 블로그입니다.
email: ccg700@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  ZzangGeun의 블로그입니다. 
  프로그래밍, 개발 경험, 그리고 일상을 기록합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ZzangGeun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: ZzangGeun

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Rouge syntax highlighting settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Rouge configuration
rouge:
  default_lang: python
  line_numbers: false

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# SEO settings
lang: ko_KR
timezone: Asia/Seoul

# Social media settings
social:
  name: ZzangGeun
  links:
    - https://github.com/ZzangGeun

# Google Analytics (uncomment and add your tracking ID when ready)
# google_analytics: UA-XXXXXXXXX-X

# Disqus comments (uncomment and add your shortname when ready)
# disqus:
#   shortname: your-disqus-shortname

# Minima theme settings
minima:
  skin: dark
  social_links:
    github: ZzangGeun
  date_format: "%Y년 %m월 %d일"

# Show excerpts on homepage
show_excerpts: true

# Navigation links
header_pages:
  - about.md
  - archive.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - "*.gem"
  - "*.gemspec"
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
