name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Create staticman.yml from template
      run: |
        cp staticman.yml.template staticman.yml
        sed -i 's/YOUR_SITE_KEY_HERE/${{ secrets.RECAPTCHA_SITE_KEY }}/g' staticman.yml
        sed -i 's/YOUR_ENCRYPTED_SECRET_HERE/${{ secrets.RECAPTCHA_SECRET }}/g' staticman.yml

    - name: Build with Jekyll
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
